import {VERSION,SUBJECTS,BASE,Store,uid,esc,link,dateKey,validDate,pd,addDays,daysBetween,weekDays,mins,clock,cfg,generate,tasksFor,materialize,stats,progress,timerElapsed,splitInterval,validateQuestions} from './core.js?v=5';
import {QUESTIONS,available,grade,shuffle} from './questions.js';
import {Cloud} from './cloud.js';
const $=id=>document.getElementById(id), store=new Store(), cloud=new Cloud(store);
let date=dateKey(),view='today',authMode='login',toastHandle,renderHandle,autoHandle;
const requested=new URLSearchParams(location.search).get('date');if(validDate(requested))date=requested;
let current=null,chosen=[],submitted=false,questionStarted=0,roundSeen=new Set(),round=1,feedback=null;
let timer=null;
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastHandle);toastHandle=setTimeout(()=>$('toast').hidden=true,4200)}
function open(id){if(!$(id).open)$(id).showModal()}
function close(id){$(id).close()}
function dateText(d){return new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long'}).format(pd(d))}
function allQuestions(){return [...QUESTIONS,...store.all('question')]}
function sourceHTML(q){const url=link(q.source?.url||'');return `<div class="question-source">${url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(q.source?.title||'查看来源')} ↗</a>`:esc(q.source?.title||'未提供来源')}<br>${esc(q.source?.level||'用户资料，未独立核验')}</div>`}
function setView(v){view=['today','practice','progress'].includes(v)?v:'today';document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('viewName').textContent=({today:'今日计划',practice:'随手练题',progress:'复习总览'})[view];$('viewToday').hidden=view!=='today';$('studyGrid').hidden=view==='progress';$('viewProgress').hidden=view!=='progress';$('reflection').hidden=view!=='today';if(view==='progress')clearTimeout(autoHandle);render();window.scrollTo({top:0,behavior:'instant'})}
function render(){renderMetrics();renderWeek();renderBoards();renderStages();renderQuizStats();renderHistory();renderCloud();diaryStatus();$('activeDate').value=date;$('dayLabel').textContent=dateText(date);$('helloDate').textContent=dateText(dateKey())+' · YOUR STUDY SPACE';const c=cfg(store);$('greeting').innerHTML=c.name?`${esc(c.name)}，<em>每一步都算数。</em>`:'把每一步，<em>都看得见。</em>';$('planHint').textContent=date<c.start?`新计划从 ${c.start} 开始。可以点上方日期查看或调整起始日。`:'日期表示计划，勾选才计入完成；未设时长的任务可自由计时。';if(document.activeElement!==$('dailyNote'))$('dailyNote').value=store.get('note',date)?.text||'';$('storageWarning').hidden=!store.error;$('storageWarning').textContent=store.error||'';updateTimer()}
function renderMetrics(){const s=stats(tasksFor(store,date)),week=weekDays(date).flatMap(d=>tasksFor(store,d)),w=stats(week);$('dayCount').innerHTML=`${s.done} <small>/ ${s.total} 项</small>`;$('dayPct').textContent=s.pct+'%';$('dayRing').style.setProperty('--p',s.pct);$('plannedMinutes').textContent=s.minutes?`已设时长 ${s.minutes} min`:'未设时长可单独定时';$('weekPct').innerHTML=w.pct+'<small>%</small>';$('weekCount').textContent=`${w.done} / ${w.total} 项 · 包含本周计划`;const sessions=store.all('focus'),todaySec=sessions.filter(x=>x.date===dateKey()).reduce((n,x)=>n+(+x.seconds||0),0),allSec=sessions.reduce((n,x)=>n+(+x.seconds||0),0);$('focusToday').innerHTML=`${Math.floor(todaySec/60)} <small>min</small>`;$('focusAll').textContent='累计 '+mins(allSec);const exam=cfg(store).examDate;$('examDays').innerHTML=validDate(exam)?`${Math.max(0,daysBetween(exam,dateKey()))} <small>天</small>`:'未设置'}
function renderWeek(){$('weekStrip').innerHTML=weekDays(date).map((d,i)=>{const s=stats(tasksFor(store,d));return `<button class="week-day ${date===d?'active':''}" data-date="${d}" aria-label="${d}，已完成${s.done}项"><div class="daytop"><span>周${'一二三四五六日'[i]}</span><b>${pd(d).getDate()}</b></div><div class="mini-progress"><i style="width:${s.pct}%"></i></div><small>${s.done}/${s.total} 完成</small></button>`}).join('')}
function renderBoards(){const tasks=tasksFor(store,date);$('boards').innerHTML=Object.entries(SUBJECTS).map(([id,s])=>{const a=tasks.filter(t=>t.subject===id),st=stats(a);return `<article class="subject-board ${id}"><div class="board-head"><span class="subject-symbol">${s.icon}</span><div><h3>${s.name}</h3><small>${s.en}</small></div><b>${st.done} / ${st.total}</b></div><div class="task-list">${a.map(t=>`<div class="task ${t.done?'done':''}"><button class="task-check" data-toggle="${esc(t.id)}" aria-label="${t.done?'取消完成':'完成'}：${esc(t.title)}" aria-pressed="${!!t.done}">${t.done?'✓':''}</button><div><div class="task-title">${esc(t.title)}</div><div class="task-detail">${esc(t.detail||'可填写章节 / 范围')}</div><div class="task-controls"><span class="time-tag">${+t.dur>0?esc(t.dur)+' min':'自由定时'}</span>${t.pri==='high'?'<span class="priority-dot">优先</span>':''}<button data-time-task="${esc(t.id)}">▷ 计时</button><button data-edit-task="${esc(t.id)}">编辑</button></div></div></div>`).join('')||'<div class="empty-tasks">留一点弹性。<br>今天的任务由你来安排。</div>'}</div><button class="board-add" data-add-subject="${id}">＋ 添加${s.name}任务</button></article>`}).join('')}
function renderStages(){const p=progress(store),c=cfg(store),items=[['西综真题作答',p.xz,11,'起点：2020–2026 已做；订正和带背仍是独立任务。'],['生化导图',p.maps,34,'已完成起点与后续已勾选图号合并，重复图号不累加。'],['红宝书单词',p.words,57,'每日一单元；已完成单元数与计划日期分开统计。'],['Anki 卡片',p.anki,1202,'未填写过的进度默认以 0 为计划起点，可随时修正。'],['肖1000 · 马原',c.xiaoMarxDone,16,'当前为手动记录的章节起点，可在设置里更新。'],['史纲剩余课程',c.historyLeft,4,'这是起点备注，不根据日历自动宣布课程已完成。']];$('progressCards').innerHTML=items.map(([name,n,total,note],i)=>`<article class="stage-card"><div class="head"><h3>${name}</h3><b>${esc(n)} <small>${i===5?'节':'/ '+total}</small></b></div><p>${note}</p><div class="mini-progress"><i style="width:${Math.min(100,Math.max(0,(i===5?total-n:n)/total*100))}%"></i></div></article>`).join('')}
function taskById(id){return store.get('task',id)||tasksFor(store,date).find(t=>t.id===id)}
function editTask(t=null,subject='west'){if(t)materialize(store,t.date);$('taskHeading').textContent=t?'编辑任务':'添加任务';$('taskId').value=t?.id||'';$('taskSubject').value=t?.subject||subject;$('taskDate').value=t?.date||date;$('taskTitle').value=t?.title||'';$('taskDetail').value=t?.detail||'';$('taskMinutes').value=t?.dur||0;$('taskPriority').value=t?.pri||'normal';$('deleteTask').hidden=!t;open('taskDialog')}
function toggleTask(id){const t=taskById(id);if(!t)return;materialize(store,t.date);store.put('task',id,{...t,done:!t.done});renderBoards();renderMetrics();renderStages()}
$('taskForm').addEventListener('submit',e=>{e.preventDefault();const id=$('taskId').value||uid(),old=store.get('task',id),d=$('taskDate').value,title=$('taskTitle').value.trim(),dur=Number($('taskMinutes').value);if(!title||!validDate(d)||!Number.isInteger(dur)||dur<0||dur>1440)return toast('请检查任务名称、日期和时长');materialize(store,d);let units=old?.units?structuredClone(old.units):undefined;const wm=title.match(/红宝书\s*[·:：]?\s*Unit\s*(\d{1,2})/i);if(old?.units?.words||wm){units=units||{};if(wm&&+wm[1]>=1&&+wm[1]<=57)units.words=[+wm[1]];else delete units.words}store.put('task',id,{...old,id,date:d,subject:$('taskSubject').value,title,detail:$('taskDetail').value.trim(),dur,pri:$('taskPriority').value,done:old?.done||false,...(units&&Object.keys(units).length?{units}:{units:undefined})});date=d;close('taskDialog');render();toast('任务已保存')});
$('deleteTask').onclick=()=>{if(confirm('删除这项任务？删除会同步到你的账号，其他任务不受影响。')){store.del('task',$('taskId').value);close('taskDialog');render()}};
const fields=[['name','怎样称呼你','text'],['examDate','考试日期（自行设置）','date'],['start','总计划起始日','date'],['xzAnchor','西综四日循环起始日','date'],['enAnchor','英语四日循环起始日','date'],['enStartYear','英语下一套年份','years'],['redbookDone','红宝书已完成起点 / 57','number',57],['bioMapsDone','生化导图已完成起点 / 34','number',34],['ankiDone','Anki 已完成起点 / 1202','number',1202],['hulusiBlock','葫芦丝当前板块','text'],['historyLeft','史纲视频剩余课程起点','number',100],['xiaoMarxDone','肖1000 马原已完成章节 / 16','number',16]];
function openSettings(){const c=cfg(store);$('settingsFields').innerHTML=fields.map(([id,label,type,max])=>`<label>${label}${type==='years'?`<select name="${id}">${[2025,2023,2021,2020,2019,2018,2017,2016].map(y=>`<option ${+c[id]===y?'selected':''}>${y}</option>`).join('')}</select>`:`<input name="${id}" type="${type}" value="${esc(c[id]??'')}" ${type==='number'?`min="0" max="${max}" step="1"`:''} ${type==='date'&&id!=='examDate'?'required':''} ${type==='text'?'maxlength="100"':''}>`}</label>`).join('')+`<label class="check-label wide"><input name="essayAlt" type="checkbox" ${c.essayAlt?'checked':''}>作文模板隔天背诵（30 分钟）</label><label class="check-label wide"><input name="protectReserved" type="checkbox" ${c.protectReserved?'checked':''}>保护英语 2022 / 2024 / 2026 模拟卷，不随机抽取</label>`;open('settingsDialog')}
$('settingsForm').onsubmit=e=>{e.preventDefault();const c=cfg(store),f=new FormData(e.target);for(const[id,,type,max]of fields){const v=f.get(id);if(type==='number'){const n=Number(v);if(!Number.isInteger(n)||n<0||n>max)return toast('进度数字超出范围');c[id]=n}else if(type==='date'){if(v&&!validDate(v))return toast('日期格式不正确');c[id]=v}else c[id]=type==='years'?+v:String(v).trim()}
 c.essayAlt=f.has('essayAlt');if(!f.has('protectReserved')&&c.protectReserved&&!confirm('解除保护后，练题可能提前出现保留模拟卷的内容。确认解除？'))return;c.protectReserved=f.has('protectReserved');store.put('cfg','plan',c);close('settingsDialog');roundSeen.clear();nextQuestion();render();toast('已保存。已有日期的任务不强制覆盖，需要时可在“数据与题库”重建当日计划。')};
// Quiz: one submission per display, unlimited displays. Statistics retain repeat attempts separately.
function quizFilters(){return{subject:$('quizSubject').value,mode:$('quizMode').value,kind:$('quizKind').value,protect:cfg(store).protectReserved}}
function nextQuestion(){clearTimeout(autoHandle);const pool=available(allQuestions(),store.all('attempt'),quizFilters());let candidates=pool.filter(q=>!roundSeen.has(q.id));if(!candidates.length&&pool.length){roundSeen.clear();round++;candidates=pool.filter(q=>pool.length===1||q.id!==current?.id)}current=shuffle(candidates)[0]||null;chosen=[];submitted=false;feedback=null;questionStarted=Date.now();if(current)roundSeen.add(current.id);renderQuestion();renderQuizStats()}
function kindName(q){return q.kind==='past'?(q.imported?'用户导入真题':'真题 · 公开整理版'):q.kind==='adapted'?'历年考点改写':'原创练习'}
function renderQuestion(){if(!current){const f=quizFilters();$('questionBody').innerHTML=`<div class="question-empty">${f.mode==='wrong'?'当前筛选下没有待重练错题。':f.mode==='unseen'?'当前筛选下的题目已全部做过。':'当前筛选下还没有可用题目。'}<p>${f.kind==='past'?'完整真题需先导入；内置题目没有冒充原题。':'可切换科目或范围，也可以导入自己的题库继续练。'}</p><button class="button" id="emptyImport">导入题库</button></div>`;$('emptyImport').onclick=()=>open('dataDialog');$('questionRound').textContent='可随时切换范围';return}
 const q=current,multi=q.answer.length>1;$('questionBody').innerHTML=`<div class="question-meta"><span class="subject-tag ${q.subject}">${SUBJECTS[q.subject]?.name||'题目'}</span><span>${esc(q.chapter)}</span><span class="kind-tag">${kindName(q)}</span><span>${multi?'多选':'单选'}${q.year?' · '+esc(q.year)+' 年 · 第 '+esc(q.number)+' 题':''}</span></div><h3 class="question-stem">${esc(q.stem)}</h3><div class="question-options">${q.options.map((o,i)=>`<button class="question-option ${chosen.includes(i)?'selected':''} ${submitted&&q.answer.includes(i)?'correct':''} ${submitted&&chosen.includes(i)&&!q.answer.includes(i)?'wrong':''}" data-choice="${i}" ${submitted?'disabled':''} aria-pressed="${chosen.includes(i)}"><span class="letter">${String.fromCharCode(65+i)}</span><span>${esc(o)}</span></button>`).join('')}</div>${submitted?`<div class="answer-result ${feedback.correct?'':'incorrect'}" role="status"><strong>${feedback.correct?'✓ 回答正确':'再理清一次'} · 答案 ${q.answer.map(i=>String.fromCharCode(65+i)).join('、')} · ${feedback.seconds}s</strong>${esc(q.explanation)}${$('autoNext').checked?`<br><small>${feedback.correct?3:8} 秒后继续；关闭“自动下一题”可停留看解析。</small>`:''}</div>`:''}<div class="question-actions"><small>${multi?'可选择多个选项，选全且不多选才算正确。':'选择一个最合适的答案。'}</small>${submitted?'<button class="button primary" id="nextQuestion">下一题 →</button>':'<button class="button primary" id="submitAnswer">提交答案 →</button>'}</div>${!submitted?'<button class="text-button" id="skipQuestion" style="margin-top:10px">暂时跳过，不计作答</button>':''}${sourceHTML(q)}`;
 document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{if(submitted)return;const i=+b.dataset.choice;chosen=multi?(chosen.includes(i)?chosen.filter(v=>v!==i):[...chosen,i]):[i];renderQuestion()});if(submitted)$('nextQuestion').onclick=nextQuestion;else{$('submitAnswer').onclick=submitAnswer;$('skipQuestion').onclick=nextQuestion}$('questionRound').textContent=`第 ${round} 轮 · 本轮已出现 ${roundSeen.size} 题`}
function submitAnswer(){if(!current||submitted)return;if(!chosen.length)return toast('先选择答案');submitted=true;clearTimeout(autoHandle);const q=current,a={id:uid(),questionId:q.id,subject:q.subject,chosen:[...chosen],correct:grade(q,chosen),seconds:Math.max(0,Math.round((Date.now()-questionStarted)/1000)),date:dateKey(),at:Date.now(),question:structuredClone(q)};feedback=a;store.put('attempt',a.id,a);renderQuestion();renderQuizStats();renderHistory();if($('autoNext').checked){const id=q.id;autoHandle=setTimeout(()=>{if(current?.id===id&&submitted&&$('autoNext').checked&&view!=='progress')nextQuestion()},a.correct?3000:8000)}}
function renderQuizStats(){const a=store.all('attempt'),correct=a.filter(x=>x.correct).length;$('quizToday').textContent=a.filter(x=>x.date===dateKey()).length;$('quizTotal').textContent=a.length;$('quizAccuracy').textContent=a.length?Math.round(correct/a.length*100)+'%':'—';$('quizUnique').textContent=new Set(a.map(x=>x.questionId)).size;$('bankCount').textContent=allQuestions().length+' 道 · 不限每日次数'}
function renderHistory(){const a=store.all('attempt').sort((a,b)=>b.at-a.at).slice(0,12);$('historyCount').textContent=a.length?'（最近 '+a.length+' 次）':'';$('quizHistory').innerHTML=a.map(x=>`<button class="attempt-row" data-attempt="${esc(x.id)}"><b class="${x.correct?'ok':'wrong-color'}">${x.correct?'✓':'×'}</b><span>${esc(x.question?.stem||'历史题目')}</span><small>${esc(x.seconds)}s · ${esc(x.date)}</small></button>`).join('')||'<p class="muted">完成第一道题后，记录会出现在这里。</p>';document.querySelectorAll('[data-attempt]').forEach(b=>b.onclick=()=>{const a=store.get('attempt',b.dataset.attempt),q=a?.question;if(!q)return;$('answerReview').innerHTML=`<div class="question-meta">${kindName(q)} · ${a.correct?'答对':'答错'} · ${esc(a.date)}</div><h3 class="question-stem">${esc(q.stem)}</h3><p>你的答案：${a.chosen.map(i=>String.fromCharCode(65+i)).join('、')}　正确答案：${q.answer.map(i=>String.fromCharCode(65+i)).join('、')}</p><div class="answer-result">${esc(q.explanation)}</div>${sourceHTML(q)}`;open('answerDialog')})}
for(const id of ['quizSubject','quizMode','quizKind'])$(id).onchange=()=>{roundSeen.clear();round=1;nextQuestion()};$('autoNext').onchange=()=>{clearTimeout(autoHandle);store.put('cfg','practice',{autoNext:$('autoNext').checked});if(submitted)renderQuestion()};
// Focus timer. Timestamp-based, not interval-decrement based. Running timer is local to a tab.
function timerKey(scope=store.scope){return 'kaoyanfuxi:timer:'+scope}
function saveTimer(){if(timer)sessionStorage.setItem(timerKey(timer.scope),JSON.stringify(timer));else sessionStorage.removeItem(timerKey())}
function loadTimer(){try{const t=JSON.parse(sessionStorage.getItem(timerKey())||'null');timer=t&&t.id&&['up','down'].includes(t.mode)&&Number.isFinite(t.base)&&Number.isFinite(t.since)&&Array.isArray(t.segments)?t:null}catch{timer=null}}
function settleTimer(){if(!timer?.running)return;const now=Date.now(),elapsed=timerElapsed(timer,now),delta=Math.max(0,elapsed-timer.base);if(delta)timer.segments.push([timer.since,timer.since+delta*1000]);timer.base=elapsed;timer.running=false;saveTimer()}
function beep(){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const a=new C(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);g.gain.value=.04;o.frequency.value=660;o.start();g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.45);o.stop(a.currentTime+.45);setTimeout(()=>a.close(),600)}catch{}}
function updateTimer(){if(timer?.running&&timer.mode==='down'&&timerElapsed(timer)>=timer.target){settleTimer();timer.finished=true;saveTimer();beep();toast('本段计时结束。可以结束记录，也可以完成关联任务。')}
 $('timerFloat').hidden=!timer;if(timer)$('timerFloat').textContent=(timer.running?'◷ ':'Ⅱ ')+clock(timer.mode==='down'?Math.ceil(timer.target-timerElapsed(timer)):timerElapsed(timer))+' · 返回专注';$('timerIdle').hidden=!!timer;$('timerActive').hidden=!timer;$('finishTaskTimer').hidden=!timer?.taskId;document.querySelector('.timer-card').classList.toggle('timer-finished',!!timer?.finished);
 if(!timer){$('timerClock').textContent='25:00';$('timerCaption').textContent='选一个任务，或直接开始';$('timerTitle').textContent='不赶进度，只专注此刻。';$('timerModeLabel').textContent='自由计时';$('timerFace').style.setProperty('--p',0);document.title='研途 · 把每一步，都看得见';return}
 const elapsed=timerElapsed(timer),shown=timer.mode==='down'?Math.ceil(timer.target-elapsed):Math.floor(elapsed);$('timerClock').textContent=clock(shown);$('timerModeLabel').textContent=timer.mode==='down'?'倒计时':'正计时';$('timerCaption').textContent=timer.finished?'计时结束 · 等待记录':timer.running?'这一段，只做眼前的事':'已暂停 · 不累计暂停时间';$('timerTitle').textContent=timer.title;$('pauseTimer').textContent=timer.running?'暂停':'继续';$('pauseTimer').disabled=!!timer.finished;$('timerFace').style.setProperty('--p',timer.mode==='down'?elapsed/timer.target*100:0);document.title=clock(shown)+' · '+timer.title+' · 研途'}
function openTimer(task=null,preset=null){const tasks=tasksFor(store,date);$('timerTask').innerHTML='<option value="">不关联任务 · 自由专注</option>'+tasks.map(t=>`<option value="${esc(t.id)}">${esc(t.title)}</option>`).join('');$('timerTask').value=task?.id||'';$('timerMode').value='down';const seconds=(preset??(task?.dur||25))*60;$('timerHours').value=Math.floor(seconds/3600);$('timerMinutes').value=Math.floor(seconds%3600/60);$('timerSeconds').value=seconds%60;$('timerCustomTitle').value=task?.title||'';setTimerMode();open('timerDialog')}
function setTimerMode(){const up=$('timerMode').value==='up';$('timeInputs').hidden=up;for(const id of ['timerHours','timerMinutes','timerSeconds'])$(id).disabled=up}
$('timerMode').onchange=setTimerMode;$('timerTask').onchange=()=>{const t=taskById($('timerTask').value);if(t)$('timerCustomTitle').value=t.title};
$('timerForm').onsubmit=e=>{e.preventDefault();const mode=$('timerMode').value,h=+$('timerHours').value,m=+$('timerMinutes').value,s=+$('timerSeconds').value,target=h*3600+m*60+s;if(mode==='down'&&(![h,m,s].every(Number.isInteger)||h<0||h>24||m<0||m>59||s<0||s>59||(target<=0||target>86400)))return toast('倒计时请设为 1 秒至 24 小时');if(timer&&!confirm('结束并记录正在进行的计时，然后开始新的一段？'))return;if(timer)finishFocus(false);const t=taskById($('timerTask').value);if(t)materialize(store,t.date);timer={id:uid(),scope:store.scope,taskId:t?.id||null,title:$('timerCustomTitle').value.trim()||t?.title||'自由专注',subject:t?.subject||'',mode,target:mode==='down'?target:0,base:0,since:Date.now(),running:true,segments:[],finished:false};saveTimer();close('timerDialog');updateTimer();toast('开始计时；可随时暂停或结束')};
function finishFocus(mark){if(!timer)return;settleTimer();const t=timer,secondsByDate={};for(const[start,end]of t.segments)for(const p of splitInterval(start,end))secondsByDate[p.date]=(secondsByDate[p.date]||0)+p.seconds;timer=null;sessionStorage.removeItem(timerKey(t.scope));for(const[d,seconds]of Object.entries(secondsByDate)){if(seconds<=0)continue;const id=t.id+'-'+d;store.put('focus',id,{id,date:d,seconds,taskId:t.taskId,title:t.title,subject:t.subject,at:Date.now()})}if(mark&&t.taskId){const task=store.get('task',t.taskId);if(task)store.put('task',task.id,{...task,done:true})}render();toast(mark?'已记录专注时间，并勾选任务':'本次计时已记录')}
$('pauseTimer').onclick=()=>{if(!timer||timer.finished)return;if(timer.running)settleTimer();else{timer.running=true;timer.since=Date.now();saveTimer()}updateTimer()};$('finishTimer').onclick=()=>finishFocus(false);$('finishTaskTimer').onclick=()=>finishFocus(true);$('timerFloat').onclick=()=>{if(view==='progress')setView('practice');document.querySelector('.timer-card').scrollIntoView({behavior:'smooth',block:'center'})};$('startFreeTimer').onclick=$('customTimer').onclick=$('sidebarTimer').onclick=()=>openTimer();document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>openTimer(null,+b.dataset.preset));setInterval(updateTimer,500);document.addEventListener('visibilitychange',updateTimer);
// Authentication is real only when an authorized backend is configured.
function renderCloud(){const s=cloud.status;$('syncLabel').textContent=store.error?'本机保存失败':cloud.message;$('syncBtn').className='sync-pill '+s;$('accountBtn').textContent=cloud.user?'我':'登';$('footerStorage').textContent=cloud.user?cloud.message+' · 账号隔离保存':cloud.configured?'未登录 · 数据仅保存在此浏览器':'云端尚未配置 · 仅本机保存';$('cloudUnavailable').hidden=cloud.configured;$('signedIn').hidden=!cloud.user;$('signedOut').hidden=!!cloud.user;$('accountEmail').textContent=cloud.user?.email||'';$('syncDetail').textContent=cloud.message+(cloud.lastError&&s==='error'?'：'+cloud.lastError:'');$('authSubmit').disabled=!cloud.ready;$('forgotPassword').disabled=!cloud.ready;$('resolveConflicts').hidden=!Object.keys(store.conflicts).length}
function openAccount(){renderCloud();$('authMessage').textContent='';open('accountDialog')}
$('accountBtn').onclick=$('syncBtn').onclick=openAccount;
for(const b of document.querySelectorAll('[data-auth-mode]'))b.onclick=()=>{authMode=b.dataset.authMode;document.querySelectorAll('[data-auth-mode]').forEach(x=>x.classList.toggle('active',x===b));$('authSubmit').textContent=authMode==='login'?'登录并同步':'创建账号';$('authPassword').autocomplete=authMode==='login'?'current-password':'new-password'};
function readableError(e){const m=e?.message||String(e);return ({'Invalid login credentials':'邮箱或密码不正确','Email not confirmed':'请先在邮箱中确认注册','User already registered':'此邮箱已注册，请直接登录','Failed to fetch':'网络暂不可用，请稍后重试'})[m]||m}
$('authForm').onsubmit=async e=>{e.preventDefault();$('authSubmit').disabled=true;$('authMessage').textContent='正在处理…';try{const email=$('authEmail').value.trim(),password=$('authPassword').value;if(authMode==='login'){await cloud.login(email,password);$('authMessage').textContent='已登录。同步状态以页面提示为准。'}else{const active=await cloud.signup(email,password);$('authMessage').textContent=active?'账号已创建。':'请查看邮箱中的确认邮件；确认后再登录。'}$('authPassword').value=''}catch(err){$('authMessage').textContent=readableError(err)}finally{renderCloud()}};
$('forgotPassword').onclick=async()=>{if(!$('authEmail').checkValidity()||!$('authEmail').value)return toast('请先填写有效邮箱');try{await cloud.reset($('authEmail').value.trim());$('authMessage').textContent='请求已提交。若该邮箱已注册且邮件服务可用，将收到重设密码邮件。'}catch(e){$('authMessage').textContent=readableError(e)}};
$('syncNow').onclick=()=>cloud.sync();$('logout').onclick=async()=>{try{if(timer&&confirm('退出前，记录本次计时？'))finishFocus(false);await cloud.logout();toast('已退出当前设备；未上传记录仍保留在该账号的本机缓存中')}catch(e){toast(readableError(e))}};
$('mergeGuest').onclick=()=>{if(!cloud.user)return;if(!confirm('将此浏览器访客记录合并到当前账号？同一编号已存在的记录将跳过，不覆盖云端。'))return;try{const guest=JSON.parse(localStorage.getItem('kaoyanfuxi:v4:guest')||'null');let n=0;for(const r of Object.values(guest?.records||{})){const k=r.bucket+':'+r.record_id;if(!store.records[k]){store.put(r.bucket,r.record_id,r.payload,r.deleted);n++}}render();cloud.sync();toast(`已合并 ${n} 条记录；可查看同步状态`)}catch(e){toast('访客记录无法读取：'+readableError(e))}};
cloud.addEventListener('account',()=>{if(timer?.running)settleTimer();loadTimer();roundSeen.clear();round=1;$('autoNext').checked=store.get('cfg','practice')?.autoNext!==false;nextQuestion();render()});
cloud.addEventListener('change',()=>{renderCloud();if(['synced','conflict'].includes(cloud.status))render()});cloud.addEventListener('recovery',()=>open('passwordDialog'));
$('passwordForm').onsubmit=async e=>{e.preventDefault();try{await cloud.password($('newPassword').value);$('newPassword').value='';$('passwordMessage').textContent='密码已更新。'}catch(e){$('passwordMessage').textContent=readableError(e)}};
function renderConflicts(){$('conflictList').innerHTML=Object.entries(store.conflicts).map(([k,c])=>`<div class="conflict-item"><h3>${esc(c.local.payload?.title||c.local.payload?.text?.slice(0,50)||k)}</h3><small>本机版本</small><pre>${esc(JSON.stringify(c.local.payload,null,2))}</pre><small>云端版本（版本号 ${c.remote.revision}）</small><pre>${esc(JSON.stringify(c.remote.payload,null,2))}</pre><div class="inline-actions"><button class="button" data-conflict="${esc(k)}" data-choice-version="local">保留本机版本</button><button class="button" data-conflict="${esc(k)}" data-choice-version="remote">使用云端版本</button></div></div>`).join('')||'<p class="muted">没有待处理的冲突。</p>';document.querySelectorAll('[data-conflict]').forEach(b=>b.onclick=()=>{store.resolve(b.dataset.conflict,b.dataset.choiceVersion);renderConflicts();render();cloud.sync()})}
$('resolveConflicts').onclick=()=>{renderConflicts();open('conflictDialog')};
// Data imports merge after explicit confirmation. Imported exam text stays private.
function downloadJSON(name,data){const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000)}
function downloadFile(name,content,type='text/plain;charset=utf-8'){const u=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000)}
function diaryNotes(){return store.all('note').map(n=>({date:String(n.id||''),text:String(n.text||'').trim()})).filter(n=>validDate(n.date)&&n.text).sort((a,b)=>a.date.localeCompare(b.date))}
function diaryStatus(){const notes=diaryNotes(),el=$('diaryStatus');if(el)el.textContent=notes.length?'目前已保存 '+notes.length+' 天的文字 · '+notes[0].date+' 至 '+notes[notes.length-1].date:'还没有可导出的每日文字。'}
function diaryHTML(notes){const entries=notes.map(n=>'<section class="entry"><div class="date">'+esc(new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(pd(n.date)))+'</div><div class="text">'+esc(n.text).replace(/\\n/g,'<br>')+'</div></section>').join('');return '<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>研途 · 每日记录</title><style>body{margin:0;background:#f5f4ef;color:#263b33;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC","Microsoft YaHei",sans-serif}.book{width:min(820px,calc(100% - 36px));margin:0 auto;padding:72px 0 90px}.cover{padding-bottom:38px;border-bottom:1px solid #dde3d8}.eyebrow{font-size:12px;letter-spacing:2px;color:#8c9b82}.cover h1{font-size:40px;font-weight:560;margin:10px 0 8px}.cover p{color:#8a9385;line-height:1.8}.entry{padding:30px 0;border-bottom:1px solid #e0e5dc}.date{font-size:14px;color:#738668;margin-bottom:14px}.text{font-size:18px;line-height:2;white-space:normal}.foot{margin-top:34px;color:#a1aa9b;font-size:12px}@media(max-width:600px){.book{padding-top:38px}.cover h1{font-size:32px}.text{font-size:17px}}@media print{body{background:white}.book{width:auto;padding:24px}.entry{break-inside:avoid}}</style></head><body><main class="book"><header class="cover"><div class="eyebrow">STUDY DESK · DAILY NOTES</div><h1>研途 · 每日记录</h1><p>共 '+notes.length+' 天 · 导出于 '+esc(dateKey())+'</p></header>'+entries+'<div class="foot">这些文字按保存日期整理，内容保持原样。</div></main></body></html>'}
function exportDiary(html=true){const notes=diaryNotes();if(!notes.length)return toast('还没有可导出的每日文字');if(html){downloadFile('研途每日记录-'+dateKey()+'.html',diaryHTML(notes),'text/html;charset=utf-8')}else{const parts=['研途 · 每日记录','共 '+notes.length+' 天',''];for(const n of notes){parts.push('【'+new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(pd(n.date))+'】',n.text,'')}downloadFile('研途每日记录-'+dateKey()+'.txt',parts.join('\\n'))}}
$('exportDiary').onclick=()=>exportDiary(true);
$('exportDiaryText').onclick=()=>exportDiary(false);
$('exportData').onclick=()=>downloadJSON('研途备份-'+dateKey()+'.json',store.export());
$('importData').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>20000000)throw Error('备份超过 20MB，请拆分或检查文件');const data=JSON.parse(await file.text());if(confirm('将备份合并到当前空间？同一记录编号会采用导入值。建议先导出当前备份。')){store.import(data);render();nextQuestion();toast('备份已合并')}}catch(err){toast(readableError(err))}e.target.value=''};
$('questionTemplate').onclick=()=>downloadJSON('研途题库导入模板.json',{format:'kaoyanfuxi-question-bank-v1',notes:'示例为原创。真题 kind 填 past，并提供 year、number、source。answer 使用0起始编号，多选如[0,2]。导入前请核验答案和使用权限。',questions:[{id:'my-question-001',subject:'eng',chapter:'语法',kind:'original',year:null,number:'',stem:'She is used to ___ detailed notes.',options:['write','writing','wrote','writes'],answer:[1],explanation:'be used to 后接名词或动名词，表示习惯于。',source:{title:'Cambridge English Grammar Today',url:'https://dictionary.cambridge.org/grammar/british-grammar/word-choice-used-to-and-be-used-to'}}]});
$('importQuestions').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>12000000)throw Error('题库超过 12MB，请分批导入');const questions=validateQuestions(JSON.parse(await file.text()));if(!confirm(`导入 ${questions.length} 道题到当前${cloud.user?'账号':'访客空间'}？请确认有权使用这些题目，且年份和答案已核验。`))return;for(const q of questions)store.put('question',q.id,q);$('importStatus').textContent=`已导入 ${questions.length} 道题。真题标签表示用户声明的来源，未伪称官方核验。`;roundSeen.clear();nextQuestion();toast('题库已更新')}catch(err){$('importStatus').textContent=readableError(err)}finally{e.target.value=''}};
$('rebuildPlan').onclick=()=>{if(!confirm('重建所选日的默认计划？保留已完成任务和自建任务；未完成的自动生成任务会按当前设置重排。'))return;materialize(store,date);for(const t of store.all('task').filter(t=>t.date===date&&!t.done&&t.id.startsWith(date+'-')))store.del('task',t.id);for(const t of generate(date,cfg(store))){const existing=store.get('task',t.id);if(!existing?.done)store.put('task',t.id,t)}render();toast('当日默认计划已重建')};
function search(){const q=$('searchInput').value.trim().toLowerCase();if(!q){$('searchResults').innerHTML='<p class="muted">可检索已保存任务、当前日期的计划和题库。保留模拟卷中的题目不会出现在检索结果中。</p>';return}const saved=store.all('task'),map=new Map([...saved,...tasksFor(store,date)].map(t=>[t.id,t])),ts=[...map.values()].filter(t=>(t.title+' '+t.detail+' '+t.date+' '+SUBJECTS[t.subject]?.name).toLowerCase().includes(q)).slice(0,30),qs=available(allQuestions(),[],{protect:cfg(store).protectReserved}).filter(t=>(t.stem+' '+t.chapter+' '+t.year).toLowerCase().includes(q)).slice(0,20);$('searchResults').innerHTML=ts.map(t=>`<button class="search-result" data-search-task="${esc(t.id)}"><b>${esc(t.title)}</b><small>${esc(t.date)} · ${SUBJECTS[t.subject]?.name||''} · ${t.done?'已完成':'未完成'}</small></button>`).join('')+qs.map(t=>`<button class="search-result" data-search-question="${esc(t.id)}"><b>${esc(t.stem)}</b><small>${kindName(t)} · ${esc(t.chapter)}</small></button>`).join('')||'<p class="muted">没有找到相关内容。</p>';document.querySelectorAll('[data-search-task]').forEach(b=>b.onclick=()=>{const t=map.get(b.dataset.searchTask);date=t.date;close('searchDialog');setView('today');editTask(t)});document.querySelectorAll('[data-search-question]').forEach(b=>b.onclick=()=>{clearTimeout(autoHandle);current=allQuestions().find(t=>t.id===b.dataset.searchQuestion);chosen=[];submitted=false;feedback=null;questionStarted=Date.now();close('searchDialog');setView('practice');renderQuestion()})}
function openSearch(){open('searchDialog');$('searchInput').focus();search()}
$('searchBtn').onclick=openSearch;$('searchInput').oninput=search;document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}});
// Navigation and plan controls.
for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>setView(b.dataset.view);
for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>close(b.dataset.close);
$('prevDay').onclick=()=>{date=addDays(date,-1);render()};$('nextDay').onclick=()=>{date=addDays(date,1);render()};$('todayBtn').onclick=()=>{date=dateKey();render()};$('activeDate').onchange=e=>{if(validDate(e.target.value)){date=e.target.value;render()}};
$('weekStrip').onclick=e=>{const b=e.target.closest('[data-date]');if(b){date=b.dataset.date;render()}};
$('boards').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.toggle)toggleTask(b.dataset.toggle);if(b.dataset.editTask)editTask(taskById(b.dataset.editTask));if(b.dataset.timeTask)openTimer(taskById(b.dataset.timeTask));if(b.dataset.addSubject)editTask(null,b.dataset.addSubject)};
$('addTask').onclick=()=>editTask();$('settingsBtn').onclick=$('progressSettings').onclick=$('examBtn').onclick=openSettings;$('dataBtn').onclick=$('questionImportBtn').onclick=()=>open('dataDialog');
$('carryBtn').onclick=()=>{const prev=addDays(date,-1);if(!store.get('day',prev))return toast('昨日没有实际保存的任务，不自动创造逾期记录');const pending=tasksFor(store,prev).filter(t=>!t.done);if(!pending.length)return toast('昨日没有未完成任务');if(!confirm(`把昨日 ${pending.length} 项未完成任务移到 ${date}？同名同范围的今日任务会跳过，以免重复。`))return;materialize(store,date);const now=tasksFor(store,date);let n=0;for(const t of pending){if(now.some(v=>v.title===t.title&&v.detail===t.detail))continue;store.put('task',t.id,{...t,date,detail:t.detail+' · 从 '+prev+' 顺延'});n++}render();toast(`已移动 ${n} 项；同名重复项未移动`)};
$('dailyNote').oninput=e=>{store.put('note',date,{id:date,text:e.target.value});$('noteState').textContent=cloud.user?'已存本机 · 等待同步确认':'已保存在本机'};
store.addEventListener('change',()=>{clearTimeout(renderHandle);renderHandle=setTimeout(()=>{renderMetrics();renderQuizStats();renderStages();$('storageWarning').hidden=!store.error;$('storageWarning').textContent=store.error||''},50)});
$('autoNext').checked=store.get('cfg','practice')?.autoNext!==false;loadTimer();nextQuestion();render();cloud.init();
if(new URLSearchParams(location.search).get('view')==='practice')setView('practice');
