import {CLOUD_CONFIG} from './config.js';
const SDK='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.102.0';
function loadSDK(){return new Promise((resolve,reject)=>{if(window.supabase?.createClient)return resolve();const s=document.createElement('script');s.src=SDK;s.referrerPolicy='no-referrer';s.onload=()=>window.supabase?.createClient?resolve():reject(Error('登录组件加载失败'));s.onerror=()=>reject(Error('登录组件网络不可用，请稍后重试'));document.head.append(s);setTimeout(()=>reject(Error('登录组件加载超时；本机功能仍可用')),15000)})}
export class Cloud extends EventTarget{
 constructor(store){super();this.store=store;this.user=null;this.status='local';this.message='仅本机保存';this.busy=false;this.ready=false;this.configured=!!(CLOUD_CONFIG.url&&CLOUD_CONFIG.publishableKey);store.addEventListener('change',()=>{if(!this.busy&&this.user&&store.pending().length){this.set('pending','待同步');clearTimeout(this.debounce);this.debounce=setTimeout(()=>this.sync(),900)}});window.addEventListener('online',()=>this.sync());window.addEventListener('offline',()=>this.set('offline','离线 · 本机已保存'));document.addEventListener('visibilitychange',()=>{if(!document.hidden)this.sync()});this.interval=setInterval(()=>{if(!document.hidden)this.sync()},15000)}
 set(status,message){this.status=status;this.message=message;this.dispatchEvent(new Event('change'))}
 async init(){if(!this.configured){this.set('local','仅本机保存 · 云端待配置');return}try{const u=new URL(CLOUD_CONFIG.url);if(u.protocol!=='https:'||!u.hostname.endsWith('.supabase.co')||u.username||u.password)throw Error('云端项目地址无效');if(CLOUD_CONFIG.publishableKey.startsWith('sb_secret_'))throw Error('检测到不允许出现在浏览器的密钥');if(CLOUD_CONFIG.publishableKey.startsWith('eyJ')){const p=JSON.parse(atob(CLOUD_CONFIG.publishableKey.split('.')[1].replace(/-/g,'+').replace(/_/g,'/')));if(p.role!=='anon')throw Error('前端只允许 publishable/anon 公钥')}
 await loadSDK();this.client=window.supabase.createClient(CLOUD_CONFIG.url,CLOUD_CONFIG.publishableKey,{auth:{storageKey:'kaoyanfuxi-auth-v1',persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});this.ready=true;
 this.client.auth.onAuthStateChange((event,session)=>{setTimeout(()=>{this.sessionChanged(session);if(event==='PASSWORD_RECOVERY')this.dispatchEvent(new Event('recovery'))},0)});
 const {data,error}=await this.client.auth.getSession();if(error)throw error;this.sessionChanged(data.session);
 }catch(e){this.set('error',e.message||'云端连接失败')}}
 sessionChanged(session){const user=session?.user||null;if(this.user?.id===user?.id){if(!user)this.set('local','未登录 · 仅本机保存');return}this.user=user;this.store.switchScope(user?.id||'guest');this.dispatchEvent(new Event('account'));if(user){this.set('pending','已登录 · 正在读取云端');this.sync()}else this.set('local','未登录 · 仅本机保存')}
 need(){if(!this.ready)throw Error(this.configured?'登录组件尚未就绪，请稍后重试':'云端数据库尚未配置，当前不能注册或登录')}
 async login(email,password){this.need();const {data,error}=await this.client.auth.signInWithPassword({email,password});if(error)throw error;this.sessionChanged(data.session)}
 async signup(email,password){this.need();const {data,error}=await this.client.auth.signUp({email,password,options:{emailRedirectTo:location.origin+location.pathname}});if(error)throw error;if(data.session)this.sessionChanged(data.session);return !!data.session}
 async reset(email){this.need();const {error}=await this.client.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});if(error)throw error}
 async password(password){this.need();const {error}=await this.client.auth.updateUser({password});if(error)throw error}
 async logout(){this.need();await this.sync();const {error}=await this.client.auth.signOut({scope:'local'});if(error)throw error;this.sessionChanged(null)}
 async sync(){if(!this.user||!this.client||this.busy)return;if(!navigator.onLine){this.set('offline','离线 · 待联网同步');return}this.busy=true;const owner=this.user.id,scope=this.store.scope;const still=()=>this.user?.id===owner&&this.store.scope===scope;this.set('syncing','正在同步…');try{
 for(let start=0;;start+=500){const {data,error}=await this.client.from('kaoyan_records').select('bucket,record_id,payload,deleted,revision,updated_at').eq('user_id',owner).order('bucket').order('record_id').range(start,start+499);if(!still())return;if(error)throw error;for(const r of data)this.store.accept(r);if(data.length<500)break}
 for(const record of this.store.pending()){const sent=structuredClone(record);const {data,error}=await this.client.rpc('kaoyan_put_record',{p_bucket:sent.bucket,p_id:sent.record_id,p_payload:sent.payload,p_deleted:sent.deleted,p_expected:sent.revision});if(!still())return;if(error)throw error;if(!data?.record)throw Error('云端没有确认保存结果');this.store.accept(data.record,data.ok?sent:null)}
 if(!still())return;this.store.persist();const n=Object.keys(this.store.conflicts).length;if(n)this.set('conflict',`${n} 项修改冲突 · 待选择`);else if(this.store.pending().length)this.set('pending','仍有本机更新待同步');else{this.lastSync=new Date();this.set('synced','已同步 · '+this.lastSync.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}))}
 }catch(e){if(still()){this.store.persist();this.set('error','同步失败 · 本机记录保留');this.lastError=e.message||String(e)}}finally{this.busy=false}}
}
