import test from 'node:test';
import assert from 'node:assert/strict';
import {Store,BASE,cfg,dateKey,validDate,daysBetween,generate,progress,tasksFor,materialize,timerElapsed,splitInterval,validateQuestions,link,esc} from '../core.js';
import {QUESTIONS,available,grade,shuffle} from '../questions.js';
class MemoryStorage {constructor(){this.data=new Map()}getItem(k){return this.data.get(k)??null}setItem(k,v){this.data.set(k,String(v))}removeItem(k){this.data.delete(k)}}
function fresh(){globalThis.localStorage=new MemoryStorage();return new Store()}
test('west 4-day cycle and morning 150 minutes',()=>{const a=generate('2026-09-24',BASE);assert.equal(a.find(t=>t.id.endsWith('xz-paper')).dur,150);assert.match(a[0].detail,/上午/);const b=generate('2026-09-25',BASE);assert.match(b.find(t=>t.id.endsWith('xz-class')).title,/生理 \+ 生化/);assert.match(generate('2026-09-26',BASE).find(t=>t.id.endsWith('xz-class')).title,/病理 \+ 外科/);assert.match(generate('2026-09-27',BASE).find(t=>t.id.endsWith('xz-class')).title,/内科 \+ 人文/);assert.match(generate('2026-09-28',BASE)[0].title,/2018/)});
test('English reserved papers are not assigned in normal cycle',()=>{const titles=Array.from({length:40},(_,i)=>generate(new Date(Date.UTC(2026,8,24+i)).toISOString().slice(0,10),BASE).filter(t=>t.id.endsWith('en-paper')).map(t=>t.title)).flat();assert(!titles.some(t=>/2022|2024|2026/.test(t)));assert.match(generate('2026-09-25',BASE).find(t=>t.id.endsWith('en-paper')).title,/阅读订正/)});
test('biochemistry final maps are 3 then 2 and then 10 Anki cards',()=>{assert.deepEqual(generate('2026-09-24',BASE).find(t=>t.units?.maps).units.maps,[30,31,32]);assert.deepEqual(generate('2026-09-25',BASE).find(t=>t.units?.maps).units.maps,[33,34]);assert.deepEqual(generate('2026-09-26',BASE).find(t=>t.units?.anki).units.anki,[1,2,3,4,5,6,7,8,9,10])});
test('a date never auto-completes progress; marking does',()=>{const s=fresh();tasksFor(s,'2026-11-23');assert.equal(progress(s).words,8);materialize(s,'2026-09-24');const t=s.all('task').find(t=>t.units?.words);s.put('task',t.id,{...t,done:true});assert.equal(progress(s).words,9);s.put('task',t.id,{...t,done:false});assert.equal(progress(s).words,8)});
test('sequential word plan advances only after actual completion',()=>{const s=fresh();let w=tasksFor(s,'2026-09-24').find(t=>t.units?.words);assert.equal(w.title,'红宝书 · Unit 9');materialize(s,'2026-09-24');assert.equal(tasksFor(s,'2026-09-25').find(t=>t.units?.words).title,'红宝书 · Unit 9');w=s.all('task').find(t=>t.id==='2026-09-24-redbook');s.put('task',w.id,{...w,done:true});assert.equal(tasksFor(s,'2026-09-25').find(t=>t.units?.words).title,'红宝书 · Unit 10')});
test('sequential biochemistry plan repeats unfinished maps and starts Anki only after maps are completed',()=>{const s=fresh();materialize(s,'2026-09-24');let m=s.all('task').find(t=>t.id==='2026-09-24-bio-maps');assert.deepEqual(tasksFor(s,'2026-09-25').find(t=>t.units?.maps).units.maps,[30,31,32]);s.put('task',m.id,{...m,done:true});assert.deepEqual(tasksFor(s,'2026-09-25').find(t=>t.units?.maps).units.maps,[33,34]);materialize(s,'2026-09-25');m=s.all('task').find(t=>t.id==='2026-09-25-bio-maps');s.put('task',m.id,{...m,done:true});assert.deepEqual(tasksFor(s,'2026-09-26').find(t=>t.units?.anki).units.anki,[1,2,3,4,5,6,7,8,9,10])});
test('completed word and Anki ranges do not repeat last new item forever',()=>{const a=generate('2027-02-01',BASE);assert(!a.some(t=>t.units?.words));assert(!a.some(t=>t.units?.anki));assert(a.some(t=>t.title.includes('滚动复习')))});
test('before start date is not assigned future tasks',()=>assert.deepEqual(generate('2026-09-23',BASE),[]));
test('v3 migration preserves task states, notes, durations, exam and focus',()=>{globalThis.localStorage=new MemoryStorage();localStorage.setItem('kaoyan-v3',JSON.stringify({days:{'2026-09-23':[{id:'old',subject:'eng',title:'custom',detail:'my range',dur:37,done:true}]},rev:{'2026-09-23':'note'},focus:{'2026-09-23':3700},exam:'2026-12-20',cfg:{redbookDone:12}}));const s=new Store();assert.equal(s.get('task','old').done,true);assert.equal(s.get('task','old').dur,37);assert.equal(s.get('note','2026-09-23').text,'note');assert.equal(s.all('focus')[0].seconds,3700);assert.equal(cfg(s).redbookDone,12);assert.equal(cfg(s).examDate,'2026-12-20');assert(localStorage.getItem('kaoyan-v3'))});
test('deleted templates stay deleted; views are non-mutating',()=>{const s=fresh();assert.equal(Object.keys(s.records).length,0);tasksFor(s,'2026-09-24');assert.equal(Object.keys(s.records).length,0);materialize(s,'2026-09-24');const id=s.all('task')[0].id;s.del('task',id);assert(!tasksFor(s,'2026-09-24').some(t=>t.id===id))});
test('account namespaces do not silently import guest data',()=>{const s=fresh();s.put('note','2026-09-24',{id:'2026-09-24',text:'guest'});s.switchScope('user-a');assert.equal(s.all('note').length,0);s.put('note','2026-09-24',{id:'2026-09-24',text:'private A'});s.switchScope('user-b');assert.equal(s.all('note').length,0);s.switchScope('guest');assert.equal(s.all('note')[0].text,'guest')});
test('conflicting versions retain local and remote until chosen',()=>{const s=fresh();s.put('note','d',{id:'d',text:'local'});s.accept({bucket:'note',record_id:'d',payload:{id:'d',text:'remote'},deleted:false,revision:2});assert.equal(s.conflicts['note:d'].remote.payload.text,'remote');assert.equal(s.get('note','d').text,'local');assert.equal(s.pending().length,0);s.resolve('note:d','local');assert.equal(s.pending()[0].revision,2);assert.equal(s.pending()[0].payload.text,'local')});
test('successful save cannot discard another local edit made in-flight',()=>{const s=fresh();s.put('note','d',{id:'d',text:'first'});const sent=structuredClone(s.pending()[0]);s.put('note','d',{id:'d',text:'second'});s.accept({bucket:'note',record_id:'d',payload:{id:'d',text:'first'},deleted:false,revision:1},sent);assert.equal(s.get('note','d').text,'second');assert.equal(s.pending()[0].revision,1)});
test('same payload from two devices is not treated as a data conflict',()=>{const s=fresh();s.put('note','d',{id:'d',text:'same'});s.accept({bucket:'note',record_id:'d',payload:{id:'d',text:'same'},deleted:false,revision:1});assert.equal(s.pending().length,0);assert.equal(Object.keys(s.conflicts).length,0)});
test('single/multiple choice exact grading; no partial credit',()=>{assert(grade({answer:[2]},[2]));assert(!grade({answer:[2]},[1]));assert(grade({answer:[0,2]},[2,0]));assert(!grade({answer:[0,2]},[0]));assert(!grade({answer:[0,2]},[0,1,2]))});
test('wrong queue drops a question after latest correct attempt',()=>{const bank=[{id:'q',subject:'west',kind:'original'}];const a=[{questionId:'q',correct:false,at:1}];assert.equal(available(bank,a,{mode:'wrong'}).length,1);a.push({questionId:'q',correct:true,at:2});assert.equal(available(bank,a,{mode:'wrong'}).length,0)});
test('reserved English years are hidden for both random and search pools',()=>{const bank=[2022,2023,2024,2026].map(year=>({id:''+year,year,subject:'eng',kind:'past'}));assert.deepEqual(available(bank,[],{protect:true}).map(q=>q.year),[2023]);assert.equal(available(bank,[],{protect:false}).length,4)});
test('bank labels, answers and source URLs are complete; no fake past items',()=>{assert.equal(QUESTIONS.length,20);assert.equal(new Set(QUESTIONS.map(q=>q.id)).size,20);assert.equal(QUESTIONS.filter(q=>q.kind==='adapted').length,3);assert.equal(QUESTIONS.filter(q=>q.kind==='past').length,1);for(const q of QUESTIONS){assert(q.source.url.startsWith('https://'));assert(q.answer.every(i=>q.options[i]));assert(q.explanation)}});
test('question import rejects invalid answer indices and missing true-paper provenance',()=>{const q={subject:'eng',stem:'x',options:['a','b'],answer:[2],explanation:'x',kind:'original'};assert.throws(()=>validateQuestions([q]));assert.throws(()=>validateQuestions([{...q,answer:[0],kind:'past'}]));const good=validateQuestions([{...q,answer:[0],kind:'past',year:2020,number:'1',source:{title:'user paper'}}]);assert.equal(good[0].kind,'past');assert.throws(()=>validateQuestions([{...q,answer:[0],kind:'past',year:'bad',number:1,source:{title:'x'}}]))});
test('timestamp clock remains correct after background throttling and respects pause',()=>{const t={base:10,since:1000,running:true,mode:'down',target:150};assert.equal(timerElapsed(t,91000),100);assert.equal(timerElapsed(t,191000),150);assert.equal(timerElapsed({...t,running:false},191000),10);assert.equal(timerElapsed({...t,mode:'up'},191000),200)});
test('midnight sessions split into dated records and preserve elapsed seconds',()=>{const a=new Date(2026,8,24,23,59,50).getTime(),z=new Date(2026,8,25,0,0,10).getTime(),rows=splitInterval(a,z);assert.equal(rows.length,2);assert.equal(rows[0].seconds,10);assert.equal(rows[1].seconds,10)});
test('dates, URLs and imported display values are constrained',()=>{assert(validDate('2026-09-24'));assert(!validDate('2026-02-30'));assert.equal(daysBetween('2026-09-25','2026-09-24'),1);assert.equal(link('javascript:alert(1)'),'');assert.equal(esc('<img onerror="x">'),'&lt;img onerror=&quot;x&quot;&gt;');const s=fresh();s.put('cfg','plan',{bioMapsDone:-10,ankiDone:'NaN',start:'bad'});assert.equal(cfg(s).bioMapsDone,0);assert.equal(cfg(s).ankiDone,0);assert.equal(cfg(s).start,BASE.start)});
test('shuffling keeps all questions exactly once',()=>{const a=QUESTIONS.map(q=>q.id);assert.deepEqual([...shuffle(a)].sort(),a.sort())});
